# Generated by Django 4.1.5 on 2023-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                ("start_date", models.DateField(verbose_name="Start_Date")),
                ("end_date", models.DateField(verbose_name="End_Date")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/%Y/%m/%d",
                        verbose_name="Img",
                    ),
                ),
                ("link_to", models.TextField(verbose_name="Link")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Banner DB", "db_table": "banners",},
        ),
    ]
