# Generated by Django 4.1.5 on 2023-04-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counselor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                (
                    "sentence",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Sentence"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="counselor/%Y/%m/%d",
                        verbose_name="Img",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Counselor DB", "db_table": "counselors",},
        ),
        migrations.CreateModel(
            name="CounselorTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_tag",
                        to="counselors.counselor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Counselor_Tag DB",
                "db_table": "counselor_tags",
            },
        ),
        migrations.CreateModel(
            name="CounselorCert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_cert",
                        to="counselors.counselor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Counselor_Cert DB",
                "db_table": "counselor_certs",
            },
        ),
    ]
