# Generated by Django 4.1.5 on 2023-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('depth', models.IntegerField()),
                ('link', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'IntroChat DB',
                'db_table': 'introchat',
            },
        ),
    ]
