# Generated by Django 4.1.5 on 2023-04-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntroChat',
        ),
    ]
