# Generated by Django 4.1.5 on 2023-04-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_delete_introchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=80, verbose_name='Sentence')),
                ('depth', models.PositiveIntegerField()),
                ('link', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Message DB',
                'db_table': 'messages',
            },
        ),
    ]
