# Generated by Django 4.1.5 on 2023-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_introchat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introchat',
            name='link',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
